name: "JDownloader"
description: "A JDownloader inside Homeassistant"
version: "0.3.2"
slug: "jdownloader"
#image: "jlesage/jdownloader-2"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  5800/tcp: 5800
ports_description:
  5800/tcp: "Web Interface"
options:
  MYJDOWNLOADER_EMAIL: ""
  MYJDOWNLOADER_PASSWORD: ""
  MYJDOWNLOADER_DEVICE_NAME: "Hassio JDownloader"
schema:
  MYJDOWNLOADER_EMAIL: str
  MYJDOWNLOADER_PASSWORD: str
  MYJDOWNLOADER_DEVICE_NAME: str
webui: http://[HOST]:[PORT:5800]
panel_icon: mdi:download
startup: system